
language: generic


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux_x64" Configuration="Debug"
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux_x64" Configuration="Release"
    - os: osx
      osx_image: xcode9.4
      env: BUILD_PLATFORM="Mac_x64" Configuration="Debug"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
    - os: osx
      osx_image: xcode9.4
      env: BUILD_PLATFORM="Mac_x64" Configuration="Release"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

install:
  - export CLONE_DIR="angle"
  - export PATH=/data/bin:/data/depot_tools:$PATH
  - export GITHUB_USER="paulthomson"
  - export GITHUB_REPO="build-angle"
  - export COMMIT_ID="${TRAVIS_COMMIT}"
  - export GROUP_DOTS="github.${GITHUB_USER}"
  - export GROUP_SLASHES="github/${GITHUB_USER}"
  - export ARTIFACT="${GITHUB_REPO}"
  - export VERSION="${COMMIT_ID}"
  - export POM_FILE="${GITHUB_REPO}-${VERSION}.pom"
  - export TAG="${GROUP_SLASHES}/${ARTIFACT}/${VERSION}"
  - export CLASSIFIER="${BUILD_PLATFORM}_${Configuration}"
  - export INSTALL_DIR="${ARTIFACT}-${VERSION}-${CLASSIFIER}"
  - ./1-install-deps-travis.sh

script:
  - ./2-build-travis.sh

after_success:
  - ./3-release-travis.sh
