
language: generic

env:
  global:
    - CO=f0b30dd8bd2bd68d6aad0e161f5fc3816d5a5077

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux-x64" Configuration="Debug"
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_PLATFORM="Linux-x64" Configuration="Release"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_PLATFORM="Darwin-x64" Configuration="Debug"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_PLATFORM="Darwin-x64" Configuration="Release"

install:
  - ./1-install-deps-travis.sh
  - export PATH=/data/bin:$PATH

script:
  - echo Building ${CO}
  - git clone https://github.com/google/angle.git
  - wget https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z x depot_tools.zip -odepot_tools
  - export PATH=$(pwd)/depot_tools:$PATH
  - gclient
  - export GYP_GENERATORS=ninja
  - cd angle
  - git checkout ${CO}
  - python scripts/bootstrap.py
  - gclient sync
  - git checkout ${CO}
  - ninja -C "out/${Configuration}"
  - cd ..

after_success:
  - cd angle/out
  - INSTALL_DIR="${Configuration}" COMMIT_ID="${TRAVIS_COMMIT}" RELEASE_ZIP="${BUILD_PLATFORM}-${Configuration}" ../../3-release-travis.sh


