
version: 1.0.{branch}-{build}

image: Visual Studio 2015

clone_depth: 5

skip_tags: true

configuration:
  - Release
  - Debug

platform:
  - x64
#  - x86

install:
  - set BRANCH_TO_CO=chromium/3029
  - echo Building %BRANCH_TO_CO%
  - bash 1-install-deps-appveyor.sh
  - refreshenv
  - set PATH=%cd%\temp;%PATH%
  - git clone https://github.com/google/angle.git
  - ps: Start-FileDownload https://storage.googleapis.com/chrome-infra/depot_tools.zip
  - 7z x depot_tools.zip -odepot_tools
  - set PATH=%cd%\depot_tools;%PATH%
  - gclient
  - set GYP_GENERATORS=msvs
  - set GYP_MSVS_VERSION=2015
  - cd angle
  - git checkout %BRANCH_TO_CO%
  - python scripts\bootstrap.py
  - gclient sync
  - git checkout %BRANCH_TO_CO%
  - cd ..

build_script:
  - msbuild angle\gyp\ANGLE.sln /p:Configuration=%Configuration% /p:Platform=%Platform% /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" & msbuild /version

#artifacts:
#  - path: angle\gyp\Release_x64\shader_translator.exe
#  - path: angle\gyp\Release_Win32\shader_translator.exe

on_success:
  - cd angle\gyp
  - set INSTALL_DIR=%Configuration%_%Platform%
  - set RELEASE_ZIP=MSVC2015-%Configuration%-%Platform%
  - set COMMIT_ID=%APPVEYOR_REPO_COMMIT%
  - bash ..\..\3-release-appveyor.sh

