
version: 1.0.{branch}-{build}

image: Visual Studio 2017

clone_depth: 5

skip_tags: true

configuration:
  - Release
  - Debug

platform:
  - x64

install:
  - set "CLONE_DIR=angle"
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\temp;%APPVEYOR_BUILD_FOLDER%\depot_tools;%PATH%"
  - bash 1-install-deps-appveyor.sh
  - refreshenv
  - set "CLONE_DIR=angle"
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\temp;%APPVEYOR_BUILD_FOLDER%\depot_tools;%PATH%"
  - set "GITHUB_USER=paulthomson"
  - set "GITHUB_REPO=build-angle"
  - set "COMMIT_ID=%APPVEYOR_REPO_COMMIT%"
  - set "GROUP_DOTS=github.%GITHUB_USER%"
  - set "GROUP_SLASHES=github/%GITHUB_USER%"
  - set "ARTIFACT=%GITHUB_REPO%"
  - set "VERSION=%COMMIT_ID%"
  - set "POM_FILE=%GITHUB_REPO%-%VERSION%.pom"
  - set "TAG=%GROUP_SLASHES%/%ARTIFACT%/%VERSION%"
  - set "CLASSIFIER=Windows_x64_%Configuration%"
  - set "INSTALL_DIR=%ARTIFACT%-%VERSION%-%CLASSIFIER%"

build_script:
  - bash 2-build-appveyor.sh

on_success:
  - bash 3-release-appveyor.sh
